### ISSUE TITLE
Onboard LucasWux

### ISSUE THREAD

**Issue by tuana9a** [tuana9a/platform#98]
# TODO

Onboard @LucasWux to access our k8s cluster

- [x] Install necessary tools: `kubectl`, `kubelogin` [int128/kubelogin](https://github.com/int128/kubelogin) (login with google)
- [x] setup `kubeconfig` from scratch: write your own `kubeconfig` piece by piece
  - [x] cluster config
  - [x] user oidc config (login with google) by using `kubelogin` plugin
- [ ] authenticate with `kube-apiserver` successfully
- [ ] config `authorization` (learn more about how kubernetes handle authorization: RBAC)
  - [ ] pod management
  - [ ] configmap management
  - [ ] replicaset management
  - [ ] statefulset management

**Comment by tuana9a** [comment]
@LucasWux

Research:
- kubeconfig syntax: how authentication with kubernetes works: what is server, what is user
- write `kubeconfig` and test login with google using kubelogin plugin

Links:
- https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/
- https://kubernetes.io/docs/reference/access-authn-authz/authentication/

**Comment by tuana9a** [comment]
close as not using any more.
